#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""generate_script_reference.py – Generate README_SCRIPTS.md from module docstrings

This helper reads all `*.py` files in the same directory (the workflow folder),
extracts the first line of each module docstring, and writes a compact reference
table to `README_SCRIPTS.md`.

Why keep this in-repo?
- It keeps the script inventory up to date as files are added/renamed.
- It nudges authors toward good module docstrings (the table is only as useful as
  the first line of each docstring).

Usage
-----
    python generate_script_reference.py

The generator is intentionally lightweight: it relies only on the Python stdlib.
"""

from __future__ import annotations

import ast
from pathlib import Path
from typing import List, Tuple


def _doc_first_line(py_path: Path) -> str:
    """Return the first line of a module docstring (or '(no module docstring)')."""
    try:
        tree = ast.parse(py_path.read_text("utf-8", errors="ignore"))
        doc = ast.get_docstring(tree)
        if doc:
            return doc.strip().splitlines()[0].strip()
    except Exception:
        pass
    return "(no module docstring)"


def _has_cli(py_path: Path) -> bool:
    """Heuristic: the file likely exposes a CLI if it uses argparse + __main__."""
    txt = py_path.read_text("utf-8", errors="ignore")
    return ("argparse.ArgumentParser" in txt) and ("if __name__" in txt or "def main" in txt)


def _category(name: str) -> str:
    if name in ("bathy_main.py", "sdb_main.py"):
        return "Pipeline entrypoint"
    if name.startswith("xs_") or name.startswith("river_") or "river" in name or name.startswith("bank_") or "manning" in name:
        return "River workflow"
    if name in ("atl.py", "vis.py", "tidal.py", "swot_adjust.py") or name.startswith("s2_") or "optics" in name:
        return "Sensor/ancillary"
    if name.startswith("sdb_") or name in (
        "train.py",
        "predict.py",
        "predict_chunked.py",
        "predict_parallel.py",
        "alignment.py",
        "features.py",
        "bathy_fusion.py",
        "fusion.py",
        "sdb_uncertainty.py",
        "bathy_interp_cli.py",
        "gapfill_intelligent.py",
        "training_diversity.py",
        "spatial_cv.py",
        "adaptive_spatial_cv.py",
        "kd_estimation.py",
        "physics_integration.py",
    ):
        return "SDB/core"
    return "Utility/notes"


def build_rows(folder: Path) -> List[Tuple[str, str, str, str]]:
    rows: List[Tuple[str, str, str, str]] = []
    for py in sorted(folder.glob("*.py")):
        if py.name == Path(__file__).name:
            continue
        rows.append((_category(py.name), py.name, _doc_first_line(py), "yes" if _has_cli(py) else "no"))
    rows.sort(key=lambda r: (r[0], r[1]))
    return rows


def render_markdown(rows: List[Tuple[str, str, str, str]]) -> str:
    lines: List[str] = []
    lines.append("# Script Reference")
    lines.append("")
    lines.append("This file is generated by `generate_script_reference.py`.")
    lines.append("")
    lines.append("- **CLI?** indicates whether the script likely supports `--help` (argparse + __main__).")
    lines.append("- For workflow-level usage, start with `README_DETAILED.md` and `README_WORKFLOW.md`.")
    lines.append("")
    lines.append("## Inventory")
    lines.append("")
    lines.append("| Category | Script | Summary (from module docstring) | CLI? |")
    lines.append("|---|---|---|---|")
    for cat, name, summary, cli in rows:
        # Escape pipes in summaries
        summary = summary.replace("|", "\\|")
        lines.append(f"| {cat} | `{name}` | {summary} | {cli} |")
    lines.append("")
    lines.append("## Regenerating")
    lines.append("")
    lines.append("Run:")
    lines.append("")
    lines.append("```bash")
    lines.append("python generate_script_reference.py")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    folder = Path(__file__).resolve().parent
    rows = build_rows(folder)
    out_path = folder / "README_SCRIPTS.md"
    out_path.write_text(render_markdown(rows), encoding="utf-8")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
